# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
os.environ['QT_QPA_PLATFROM_PLUGIN_PATH']="../platforms"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 0, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 61, 31))
        self.label_3.setObjectName("label_3")
        self.txtPlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPlainText.setGeometry(QtCore.QRect(120, 110, 261, 71))
        self.txtPlainText.setObjectName("txtPlainText")
        self.txtcipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txtcipherText.setGeometry(QtCore.QRect(120, 190, 261, 71))
        self.txtcipherText.setObjectName("txtcipherText")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 140, 61, 21))
        self.label_4.setObjectName("label_4")
        self.txtsignature = QtWidgets.QTextEdit(self.centralwidget)
        self.txtsignature.setGeometry(QtCore.QRect(490, 190, 331, 71))
        self.txtsignature.setObjectName("txtsignature")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 200, 61, 31))
        self.label_5.setObjectName("label_5")
        self.txtinformation = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinformation.setGeometry(QtCore.QRect(490, 110, 331, 71))
        self.txtinformation.setObjectName("txtinformation")
        self.BtnEncypt = QtWidgets.QPushButton(self.centralwidget)
        self.BtnEncypt.setGeometry(QtCore.QRect(100, 330, 75, 23))
        self.BtnEncypt.setObjectName("BtnEncypt")
        self.BtnDecypt = QtWidgets.QPushButton(self.centralwidget)
        self.BtnDecypt.setGeometry(QtCore.QRect(230, 330, 75, 23))
        self.BtnDecypt.setObjectName("BtnDecypt")
        self.BtnSign = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSign.setGeometry(QtCore.QRect(560, 320, 75, 23))
        self.BtnSign.setObjectName("BtnSign")
        self.BtnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.BtnVerify.setGeometry(QtCore.QRect(680, 320, 75, 23))
        self.BtnVerify.setObjectName("BtnVerify")
        self.BtnGenereteKeys = QtWidgets.QPushButton(self.centralwidget)
        self.BtnGenereteKeys.setGeometry(QtCore.QRect(590, 30, 101, 23))
        self.BtnGenereteKeys.setObjectName("BtnGenereteKeys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label_4.setText(_translate("MainWindow", "Information:"))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.BtnEncypt.setText(_translate("MainWindow", "Encrypt"))
        self.BtnDecypt.setText(_translate("MainWindow", "Decrypt"))
        self.BtnSign.setText(_translate("MainWindow", "Sign"))
        self.BtnVerify.setText(_translate("MainWindow", "Verify"))
        self.BtnGenereteKeys.setText(_translate("MainWindow", "Generete Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
